### ISSUE TITLE
yolov4Transferlearn.m error

### ISSUE THREAD

**Issue by chn7960** [matlab-deep-learning/pretrained-yolo-v4#1]
About yolov4Transferlearn.m.

The following error occurred.

What is the problem?

![image](https://user-images.githubusercontent.com/45690932/130590710-e78d2194-56a5-45c8-8326-91e73edb2c54.png)

**Comment by sbairagy-MW** [comment]
@chn7960   Sorry for the delayed response.
There are two options to avoid the out of memory issues during training. 

1. You can reduce the 'miniBatchsize' (at line no. 181 of _yolov4TransferLearn.m_ file) and train the model. The current 'miniBatchSize' is 4, you can reduce it to a smaller size depending upon your GPU memory. 

2. You can change the 'networkInputSize' (at line no. 108 of  _yolov4TransferLearn.m_ file) to a smaller input size, say [416,416,3] and train the model. You will have to change the 'inputSize' in _detectYOLOv4.m_ (at line no. 21 of _detectYOLOv4.m_ file) to the input size that you specified during training, say [416,416,3] to correctly perform the inference.

Please try this and let me know if you face any additional issues.

**Comment by trandong20** [comment]
thank you all for the help, but when i train my own data, the following error appear, how do i solve the problem, thank you
![image](https://user-images.githubusercontent.com/96462192/147810389-64737763-b567-4eb7-9353-98f7f0fe386e.png)
