### ISSUE TITLE
codegen error

### ISSUE THREAD

**Issue by chn7960** [matlab-deep-learning/pretrained-yolo-v4#2]
When I run codegenYOLOv4.m, an error like the attached image occurs.
![캡처ddddddd](https://user-images.githubusercontent.com/45690932/138237022-5eef13c9-0930-480c-a9a7-87280d35af81.PNG)

**Comment by sbairagy-MW** [comment]
@chn7960 It seems that the system might not have the GPU Mex compiler supported for codegen.
