### ISSUE TITLE
convert to ONNX

### ISSUE THREAD

**Issue by ssda35** [matlab-deep-learning/pretrained-yolo-v4#3]
Hi,
Can you tell me to convert the model to ONNX, please?

**Comment by viakkala** [comment]
You can use the following command:
exportONNXNetwork(net,filename)
For more information on how to export network to ONNX, see [exportONNXNetwork](https://www.mathworks.com/help/deeplearning/ref/exportonnxnetwork.html).

Note: Pretrained YOLO v4 network has custom layers like 'mish' layer, 'slice' layer, etc., these layers will be exported as placeholder layers in ONNX. Please make sure to replace them accordingly.
