### ISSUE TITLE
How to obtain the pixel coordinates of the bounding box?

### ISSUE THREAD

**Issue by Chezhian531** [matlab-deep-learning/pretrained-yolo-v4#7]
I am trying to get all the values of pixels inside the bounding box. Could you please help me on how to achieve this?

I understand the bounding box is normalized coordinates of the center of the bounding box. But how to really obtain the coordinates of the bounding box?

Thanks in advance

**Comment by sbairagy-MW** [comment]
@Chezhian531 

Each bounding box returned by `detectYOLOv4` function is of the format: **_[x,y,width, height]_**, where **_[x,y]_** specifies the upper left corner and **_[width,height]_** specifies the size of the bounding box in pixels.
