### ISSUE TITLE
YoloV4 "Out of memory on device" issue.

### ISSUE THREAD

**Issue by Patagonia-xxHackerman010** [matlab-deep-learning/pretrained-yolo-v4#8]
I am trying to train YoloV4, using the exact code you provided. Everything starts up, but once it wants to start the first epoch it throws an error. It always tells me "Out of memory on device", even though I have a pretty powerful GPU. I tried adjusting some settings, but can't get the error to stop. If I switch to CPU mode the code runs fine, any idea how to solve this?

`>> yolov4TransferLearn
Pretrained YOLOv4-coco network already exists.

Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 8).
Error using nnet.internal.cnn.dlnetwork/forward (line 288)
Layer 'bn_6': Invalid input data. Out of memory on device. To view more detail about available memory on the GPU, use
'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)'.

Error in nnet.internal.cnn.dlnetwork/DefaultOptimizationStrategy/propagate (line 78)
            [varargout{1:nargout}] = inferenceMethod(net, X, layerIndices, layerOutputIndices);

Error in nnet.internal.cnn.dlnetwork/DefaultOptimizationStrategy/forward (line 34)
            [varargout{1:nargout}] = propagate(strategy, net, X, ...

Error in dlnetwork/forward (line 572)
                    [varargout{1:nargout}] = strategy.forward(net.PrivateNetwork, x, layerIndices, layerOutputIndices);

Error in helper.yolov4Forward (line 8)
[YPredictions{:}, state] = forward(net, XTrain, 'Outputs', networkOutputs);

Error in modelGradients (line 39)
[YPredCell, state] = helper.yolov4Forward(net,XTrain,networkOutputs,mask);

Error in deep.internal.dlfeval (line 17)
[varargout{1:nargout}] = fun(x{:});

Error in dlfeval (line 40)
    [varargout{1:nargout}] = deep.internal.dlfeval(fun,varargin{:});

Error in yolov4TransferLearn (line 265)
        [gradients, state, lossInfo] = dlfeval(@modelGradients, net, XTrain, YTrain, anchorBoxes, anchorBoxMasks, penaltyThreshold, networkOutputs);
 `

**Comment by sbairagy-MW** [comment]
@Patagonia-xxHackerman010 

There are two options to avoid the out of memory issues during training.

1. You can reduce the 'miniBatchsize' (at line no. 181 of yolov4TransferLearn.m file) and train the model. The current 'miniBatchSize' is 4, you can reduce it to a smaller size depending upon your GPU memory.

2. You can change the 'networkInputSize' (at line no. 108 of yolov4TransferLearn.m file) to a smaller input size, say [416,416,3] and train the model. You will have to change the 'inputSize' in detectYOLOv4.m (at line no. 21 of detectYOLOv4.m file) to the input size that you specified during training, say [416,416,3] to correctly perform the inference.

Please try this and let me know if you face any additional issues.
