### ISSUE TITLE
Transfer Learning Script needs vehicleDatasetImages.zip

### ISSUE THREAD

**Issue by sammitjain** [matlab-deep-learning/pretrained-yolo-v4#9]
The `yolov4TransferLearn.mlx` script needs the `vehicleDatasetImages.zip` file. 

Running the script after directly cloning the repo therefore does not work. Is there a separate dataset for this exercise? I used the dataset that comes packaged with this [documented example](https://www.mathworks.com/help/vision/ug/object-detection-using-yolov4-deep-learning.html) as a workaround.

Possible solution: Include a line of code to bring the `vehicleDatasetImages.zip` file into the path, before unzipping it.

**Comment by sbairagy-MW** [comment]
@sammitjain The `vehicleDatasetImages.zip` file is added to the repository. Now, you should be able to access it.
